# Generated by Django 2.2.5 on 2019-09-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datachart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='parameter_value',
            new_name='Speed',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='parameter_name',
        ),
        migrations.AddField(
            model_name='parameter',
            name='Temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='Votage',
            field=models.IntegerField(default=0),
        ),
    ]
