# Generated by Django 2.2.5 on 2019-09-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datachart', '0002_auto_20190919_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='Votage',
            new_name='Voltage',
        ),
    ]
