# Generated by Django 2.2.5 on 2019-10-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datachart', '0003_auto_20190919_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='timestamp',
            new_name='pr_Timestamp',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='time',
            new_name='pr_time',
        ),
    ]
