# Generated by Django 2.2.5 on 2019-10-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datachart', '0004_auto_20191011_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='pr_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='pr_Timestamp',
            new_name='timestamp',
        ),
    ]
