# Generated by Django 2.2.5 on 2019-10-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datachart', '0006_auto_20191015_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='Speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='Temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='Voltage',
            field=models.IntegerField(default=0),
        ),
    ]
