# Generated by Django 3.0.2 on 2020-05-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datachart', '0008_auto_20200502_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='Current_timestamp',
            new_name='current_datetime',
        ),
    ]
